
PATHWAY_NODES_MAP = {
    "C-S-01:Organic carbon oxidation": "organic carbon -> CO2",
    "C-S-02:Carbon fixation": "CO2 -> organic carbon",
    "C-S-03:Ethanol oxidation": "ethanol -> CO2",
    "C-S-04:Acetate oxidation": "acetate -> CO2",
    "C-S-05:Hydrogen generation": "organic carbon -> H2",
    "C-S-06:Fermentation": "ethanol -> acetate",
    "C-S-07:Methanogenesis": "acetate;H2;CO2 -> CH4",
    "C-S-08:Methanotrophy": "CH4 -> CO2",
    "C-S-09:Hydrogen oxidation": "H2 -> H2O",
    "C-S-10:Acetogenesis WL": "CO2;H2 -> acetate",
    "N-S-01:Nitrogen fixation": "N2 -> NH4",
    "N-S-02:Ammonia oxidation": "NH4 -> NO2",
    "N-S-03:Nitrite oxidation": "NO2 -> NO3",
    "N-S-04:Nitrate reduction": "NO3 -> NO2",
    "N-S-05:Nitrite reduction": "NO2 -> NO",
    "N-S-06:Nitric oxide reduction": "NO -> N2O",
    "N-S-07:Nitrous oxide reduction": "N2O -> N2",
    "N-S-08:Nitrite ammonification": "NO3 -> NH4",
    "N-S-09:Anammox": "NO2;NH4 -> N2",
    "N-S-10:Nitric oxide dismutase": "NO -> N2",
    "O-S-01:Iron reduction": "Fe3+ -> Fe2+",
    "O-S-02:Iron oxidation": "Fe2+ -> Fe3+",
    "O-S-03:Arsenate reduction": "AsO4 -> AsO3",
    "O-S-04:Arsenite oxidation": "AsO3 -> AsO4",
    "O-S-05:Selenate reduction": "SeO4 -> Se0",
    "O-S-06:Aerobic respiration": "O2 -> H2O",
    "S-S-01:Sulfide oxidation": "H2S -> S0",
    "S-S-02:Sulfur reduction": "S0 -> H2S",
    "S-S-03:Sulfur oxidation": "S0 -> SO3",
    "S-S-04:Sulfite oxidation": "SO3 -> SO4",
    "S-S-05:Sulfate reduction": "SO4 -> SO3",
    "S-S-06:Sulfite reduction": "SO3 -> H2S",
    "S-S-07:Thiosulfate oxidation": "S2O3 -> SO4",
    "S-S-08:Thiosulfate disproportionation 1": "S2O3 -> S0;SO4",
    "S-S-09:Thiosulfate disproportionation 2": "S2O3 -> SO3;H2S",
    # "S-S-10:Polysulfide reduction": "" # Not used
}

ID_COLS = [
    "dataset",
    "sample_id",
    "location",
    "sublocation",
    "country",
    "latitude",
    "longitude",
    "elevation",
    "depth",
    "type",
    "lithology"
]

ENV_COLS = [
    "temperature",
    "pH",
    "conductivity",
    "ORP",
    "salinity",
    "TDS",
    "DO",
    "DOC",
    "DIC",
    "alkalinity",
    "HCO3",
    "CO",
    "CO2",
    "CH4",
    "ethane",
    "propane",
    "acetate",
    "H2",
    "NO3",
    "NO2",
    "NH4",
    "SO4",
    "HS-",
    "S2-",
    "S2O3",
    "PO4",
    "P",
    "Fe2+",
    "Fe",
    "Mn",
    "Ni",
    "Na",
    "K",
    "Ca",
    "Mg",
    "Cl",
    "Br",
    "F",
    "Cu",
    "Ge",
    "As",
    "Sr",
    "Y",
    "U",
    "Si",
    "δ18O"
]

RISK_PATHWAYS = [
    "N-S-01:Nitrogen fixation",
    "N-S-04:Nitrate reduction",
    "N-S-05:Nitrite reduction",
    "S-S-02:Sulfur reduction",
    "S-S-05:Sulfate reduction",
    "S-S-06:Sulfite reduction",
    "S-S-07:Thiosulfate oxidation",
    "S-S-08:Thiosulfate disproportionation 1",
    "S-S-09:Thiosulfate disproportionation 2",
    # "S-S-10:Polysulfide reduction",
    "C-S-02:Carbon fixation",
    "C-S-07:Methanogenesis",
    "C-S-09:Hydrogen oxidation",
    "C-S-10:Acetogenesis WL",
    "O-S-01:Iron reduction",
    "O-S-03:Arsenate reduction",
    # "O-S-06:Aerobic respiration"
]
