PATHWAY_NODE_MAP = {
    "C-S-01:Organic carbon oxidation": "oxidation-organic carbon",
    "C-S-02:Carbon fixation": "fixation-CO2",
    "C-S-03:Ethanol oxidation": "oxidation-ethanol",
    "C-S-04:Acetate oxidation": "oxidation-acetate",
    "C-S-05:Hydrogen generation": "reduction-H+",    # Generation of H2
    "C-S-06:Fermentation": "reduction-H+",           # Generation of H2
    "C-S-07:Methanogenesis": "oxidation-H2",
    "C-S-08:Methanotrophy": "oxidation-CH4",
    "C-S-09:Hydrogen oxidation": "oxidation-H2",
    "C-S-10:Acetogenesis WL": "oxidation-H2",
    "N-S-01:Nitrogen fixation": "fixation-N2",
    "N-S-02:Ammonia oxidation": "oxidation-NH4",
    "N-S-03:Nitrite oxidation": "oxidation-NO2",
    "N-S-04:Nitrate reduction": "reduction-NO3",
    "N-S-05:Nitrite reduction": "reduction-NO2",
    "N-S-06:Nitric oxide reduction": "reduction-NO",
    "N-S-07:Nitrous oxide reduction": "reduction-N2O",
    "N-S-08:Nitrite ammonification": "reduction-NO2",
    "N-S-09:Anammox": "oxidation-NH4",
    "N-S-10:Nitric oxide dismutase": "reduction-N2", # Disproportionation
    "O-S-01:Iron reduction": "reduction-Fe3+",
    "O-S-02:Iron oxidation": "oxidation-Fe2+",
    "O-S-03:Arsenate reduction": "reduction-AsO4",
    "O-S-04:Arsenite oxidation": "oxidation-AsO3",
    "O-S-05:Selenate reduction": "reduction-SeO4",
    "O-S-06:Aerobic respiration": "reduction-O2",
    "S-S-01:Sulfide oxidation": "oxidation-H2S",
    "S-S-02:Sulfur reduction": "reduction-S0",
    "S-S-03:Sulfur oxidation": "oxidation-S0",
    "S-S-04:Sulfite oxidation": "oxidation-SO3",
    "S-S-05:Sulfate reduction": "reduction-SO4",
    "S-S-06:Sulfite reduction": "reduction-SO3",
    "S-S-07:Thiosulfate oxidation": "oxidation-S2O3",
    "S-S-08:Thiosulfate disproportionation 1": "oxidation-S2O3",
    "S-S-09:Thiosulfate disproportionation 2": "oxidation-S2O3"
}

NODE_CYCLE_MAP = {
    "H2": "hydrogen",
    "H+": "hydrogen",
    "organic carbon": "carbon",
    "acetate": "carbon",
    "ethanol": "carbon",
    "CH4": "carbon",
    "CO2": "carbon",
    "S0": "sulfur",
    "H2S": "sulfur",
    "SO3": "sulfur",
    "SO4": "sulfur",
    "S2O3": "sulfur",
    "NO2": "nitrogen",
    "NO3": "nitrogen",
    "NH4": "nitrogen",
    "N2O": "nitrogen",
    "NO": "nitrogen",
    "N2": "nitrogen",
    "O2": "oxygen",
    "Fe2+": "iron",
    "Fe3+": "iron",
    "AsO3": "other",
    "AsO4": "other",
    "SeO4": "other"
}

ID_COLS = [
    "dataset",
    "sample_id",
    "location",
    "sublocation",
    "country",
    "latitude",
    "longitude",
    "elevation",
    "depth",
    "type",
    "lithology"
]

ENV_COLS = [
    "temperature",
    "pH",
    "conductivity",
    "ORP",
    "salinity",
    "TDS",
    "DO",
    "DOC",
    "DIC",
    "alkalinity",
    "HCO3",
    "CO",
    "CO2",
    "CH4",
    "ethane",
    "propane",
    "acetate",
    "H2",
    "NO3",
    "NO2",
    "NH4",
    "SO4",
    "HS-",
    "S2-",
    "S2O3",
    "PO4",
    "P",
    "Fe2+",
    "Fe",
    "Mn",
    "Ni",
    "Na",
    "K",
    "Ca",
    "Mg",
    "Cl",
    "Br",
    "F",
    "Cu",
    "Ge",
    "As",
    "Sr",
    "Y",
    "U",
    "Si",
    "δ18O"
]

RISK_PATHWAYS = [
    "N-S-01:Nitrogen fixation",
    "N-S-04:Nitrate reduction",
    "N-S-05:Nitrite reduction",
    "S-S-02:Sulfur reduction",
    "S-S-05:Sulfate reduction",
    "S-S-06:Sulfite reduction",
    "S-S-07:Thiosulfate oxidation",
    "S-S-08:Thiosulfate disproportionation 1",
    "S-S-09:Thiosulfate disproportionation 2",
    # "S-S-10:Polysulfide reduction",
    "C-S-02:Carbon fixation",
    "C-S-07:Methanogenesis",
    "C-S-09:Hydrogen oxidation",
    "C-S-10:Acetogenesis WL",
    "O-S-01:Iron reduction",
    "O-S-03:Arsenate reduction",
    # "O-S-06:Aerobic respiration"
]
